<a href="https://colab.research.google.com/github/merbiji/Computational-Physics/blob/main/PALISBO_Activity01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter_1

---



In [ ]:
print("I love Python")


I love Python


In [ ]:
import antigravity

In [ ]:
base = 10
height = 12

area = 1/2 *base*height
print(area)

60.0


In [ ]:
x1 = 3
x2 = 5
y1 = 4
y2 = 9

slope = (y2-y1)/(x2-x1)
print(slope)


2.5


In [ ]:
import math as mat

mat.factorial(6)

720

#Chapter_2

In [ ]:
PH_schools = {}

PH_schools["UP"] = "NCR"

PH_schools["MSU IIT"] = "Mindanao"

"MSU IIT" in PH_schools



True

In [ ]:
x = np.array([1,2,3],[])
y = np.array([[1, 4, 3], [9, 2, 7]])

print(x.size)
print(x.shape)
print(y.size)
print(y.shape)

3
(3,)
6
(2, 3)


In [ ]:
z = np.arange(1,2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999])

In [ ]:
np.linspace(3,9,10)

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#Chapter_3


In [ ]:
def my_test(a, b):
  x = a + b
  y = x * b
  z = a + b
  m = 2

  print(f'Within function: x={x}, y={y}, z= {z}')
  return x, y

x = 5
y =3
b, a = my_test(x, y)

print(f'Outside function: x={x}, y={y}, z={z}')



Within function: x=8, y=24, z= 8
Outside function: x=5, y=3, z=1


In [ ]:
import numpy as np

def my_dist_xyz(x,y,z):

  def my_dist(x,y):
    out = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
    return out

  d0 = my_dist(x,y)
  d1 = my_dist(x,z)
  d2 = my_dist(y,z)

  return [d0, d1, d2]

d = my_dist_xyz((0,0), (0,1),(1,1))
print(d)




[np.float64(1.0), np.float64(1.4142135623730951), np.float64(1.0)]


In [ ]:
exponent = lambda x, y: x**y

print(exponent(3,4))

81


In [ ]:
import numpy as np


def my_fun_plus_one(f,x):

  return f(x) + 1

print(my_fun_plus_one(np.sin, np.pi/2))
print(my_fun_plus_one(np.cos, np.pi/2))
print(my_fun_plus_one(np.sqrt, 25))

2.0
1.0
6.0


In [ ]:
import math as mat

def my_sinh(x):

  y=(mat.exp(x)-mat.exp(-x))/2

  return y

print(my_sinh(1))
print(my_sinh(2))



1.1752011936438014
3.626860407847019
