<a href="https://colab.research.google.com/github/merbiji/Computational-Physics/blob/main/PALISBO_Activity01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter_1

---



In [ ]:
print("I love Python")


I love Python


In [ ]:
import antigravity

In [ ]:
base = 10
height = 12

area = 1/2 *base*height
print(area)

60.0


In [ ]:
x1 = 3
x2 = 5
y1 = 4
y2 = 9

slope = (y2-y1)/(x2-x1)
print(slope)



2.5


In [1]:
import math as mat

x1 = 3
x2 = 5
y1 = 4
y2 = 9

distance = mat.sqrt((x2-x1)**2+(y2-y1)**2)
print(distance)


5.385164807134504


In [ ]:
import math as mat

mat.factorial(6)

720

In [2]:
divisible_by_4 = 2010 // 4 - 1500 // 4
divisible_by_100 = 2010 // 100 - 1500 // 100
divisible_by_400 = 2010 // 400 - 1500 // 400
leap_year = divisible_by_4 - divisible_by_100 + divisible_by_400

print(leap_year)

124


In [7]:
import math as mat

x = 2
sinh =(mat.exp(x))-(mat.exp(-x))/ 2
print(sinh)


7.321388457312344


In [14]:
import math as mat
import numpy as np

def circle(x):
   result = mat.sin(x)**2 + mat.cos(x)**2
   return result


x = np.array([mat.pi, mat.pi/2, mat.pi/4])

for ix in x:
  print(circle(ix))

1.0
1.0
1.0


In [18]:
import math as mat

y = mat.sin(mat.radians(87))
print(y)

0.9986295347545738


In [19]:
import math as mat

y = mat.sni(mat.radians(87))
print(y)

AttributeError: module 'math' has no attribute 'sni'

In [21]:
import math as mat

y = mat.sin()
print(y)

TypeError: math.sin() takes exactly one argument (0 given)

In [24]:
import math as mat

y = (mat.exp(2)) * (mat.sin(mat.pi/6)) + (mat.log(3)) * (mat.cos(mat.pi/9)) - (5)**3
print(y)

-120.27311408976854


#Chapter_2

In [28]:
s= ""
type(s)

str

In [30]:
name = "MSU IIT"
country = "Philippines"

print(f"{name} is a school in the {country}.")

MSU IIT is a school in the Philippines.


In [32]:
(print(f"{3*4}"))

12


NoneType

In [ ]:
PH_schools = {}

PH_schools["UP"] = "NCR"

PH_schools["MSU IIT"] = "Mindanao"

"MSU IIT" in PH_schools



True

In [ ]:
x = np.array([1,2,3],[])
y = np.array([[1, 4, 3], [9, 2, 7]])

print(x.size)
print(x.shape)
print(y.size)
print(y.shape)

3
(3,)
6
(2, 3)


In [ ]:
z = np.arange(1,2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999])

In [ ]:
np.linspace(3,9,10)

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
x = 2
y = 3

del x;
print(x)

NameError: name 'x' is not defined

In [ ]:
import math as mat

x = 10
y = 3
u = x + y
v = x*y
w = x/y
z = mat.sin(x)
r = 8*mat.sin(x)
s = 5*mat.sin*(x*y)
p = x**y



In [36]:
y = "Engineering"
x = "book"

print(f"The word {y} has {len(y)} letters.")
print(f"The word {x} has {len(x)} letters.")

The word Engineering has 11 letters.
The word book has 4 letters.


In [37]:
y = "Python is great"
check = "Python" in y

print(check)


True


In [41]:
x = "Python is great"
x[-5:]

'great'

In [46]:
list_a = [1,8,9,15]
list_a.insert(1,2)
list_a.append(4)

print(sorted(list_a))

[1, 2, 4, 8, 9, 15]


In [48]:
y = "Python is great!"

list(y)

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't',
 '!']

In [52]:
set_a = (2,3,2)
set_b = (1,2,3)

union = set_a + set_b
union


TypeError: can't multiply sequence by non-int of type 'tuple'

#Chapter_3


In [ ]:
def my_test(a, b):
  x = a + b
  y = x * b
  z = a + b
  m = 2

  print(f'Within function: x={x}, y={y}, z= {z}')
  return x, y

x = 5
y =3
b, a = my_test(x, y)

print(f'Outside function: x={x}, y={y}, z={z}')



Within function: x=8, y=24, z= 8
Outside function: x=5, y=3, z=1


In [ ]:
import numpy as np

def my_dist_xyz(x,y,z):

  def my_dist(x,y):
    out = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
    return out

  d0 = my_dist(x,y)
  d1 = my_dist(x,z)
  d2 = my_dist(y,z)

  return [d0, d1, d2]

d = my_dist_xyz((0,0), (0,1),(1,1))
print(d)




[np.float64(1.0), np.float64(1.4142135623730951), np.float64(1.0)]


In [ ]:
exponent = lambda x, y: x**y

print(exponent(3,4))

81


In [ ]:
import numpy as np


def my_fun_plus_one(f,x):

  return f(x) + 1

print(my_fun_plus_one(np.sin, np.pi/2))
print(my_fun_plus_one(np.cos, np.pi/2))
print(my_fun_plus_one(np.sqrt, 25))

2.0
1.0
6.0


In [ ]:
import math as mat

def my_sinh(x):

  y=(mat.exp(x)-mat.exp(-x))/2

  return y

print(my_sinh(1))
print(my_sinh(2))



1.1752011936438014
3.626860407847019


# CHAPTER 4

In [60]:
def my_tip_calc(bill, party):
  if party < 6:
    tips = bill * 0.15
  elif party < 8:
    tips = bill * 0.18
  elif party <11:
    tips = bill * 0.20
  elif party > 11:
    tips = bill * 0.25
  return tips

t = my_tip_calc(109.29,3)
print(t)


z = my_tip_calc(109.29,7)
print(z)

x = my_tip_calc(109.29,9)
print(x)

y = my_tip_calc(109.29,12)
print(y)

16.3935
19.6722
21.858000000000004
27.3225
